Processing data
Sami-Ullah-Tufail/blog pull request #2
Opened 2023-12-22 23:10 UTC by Sami-Ullah-Tufail

### This branch fulfills the following requirements

- [ ] Set up associations between models to establish relationships between Users, Posts, Comments, and Likes.
- [ ]  Implemented a method to return the 3 most recent posts for a given user (recent_posts).
- [ ]  Created a method to update the posts counter for a user (increment_user_post_counter).
- [ ]  Added a method to return the 5 most recent comments for a given post (recent_comments).
- [ ]  Created a method to update the comments counter for a post (increment_post_comments_counter).
- [ ]  Implemented a method to update the likes counter for a post (increment_post_likes_counter).

2023-12-22 23:26 UTC, zieeco requested changes
Hi @Estete9,


<img height="80" src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>



Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Great job with adding the forms.✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-22 23:26 UTC, zieeco commented on db/migrate/20231222201514_create_users.rb
> +      t.integer :post_counter, default: 0
- Hi, in your post model, you have used posts_counter, but it is singular here. kindly update it.

2023-12-22 23:26 UTC, zieeco commented on db/migrate/20231222201514_create_users.rb
> +      t.integer :post_counter, default: 0
**[OPTIONAL]**



- Let's try to add the node_mofules/ to the .gitignore file before we make a commit to prevent pushing them to your repo.

2023-12-23 11:53 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Sami-Ullah-Tufail,

✔️ Implementation of association between models

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-23 11:53 UTC, TedLivist commented on db/migrate/20231222201909_create_posts.rb
> +class CreatePost < ActiveRecord::Migration[7.1]
- [ ] **[OPTIONAL]** There is an issue with your migration. There is a mismatch in the file name and the class name. This should be `CreatePosts`

  ![image](https://github.com/Sami-Ullah-Tufail/blog/assets/36542986/de37bb67-ae29-4bfb-b374-e95f6cf5299e)

2023-12-23 11:53 UTC, TedLivist commented on db/migrate/20231222202341_like_table.rb
> +class LikesTable < ActiveRecord::Migration[7.1]
- [ ] **[OPTIONAL]** You should rename this file to `...likes_table.rb` to match the class name.

  ![image](https://github.com/Sami-Ullah-Tufail/blog/assets/36542986/cc2a8939-67a7-4f35-a979-0800eb8818cf)

2023-12-23 11:53 UTC, TedLivist commented on db/migrate/20231222202435_comment_table.rb
> +class CommentsTable < ActiveRecord::Migration[7.1]
- [ ] **[OPTIONAL]** You should rename this file to `...comments_table` to match the class name.

2023-12-23 14:41 UTC, merged